/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as onlineOrderSol from "./online_order.sol";
export type { onlineOrderSol };
import type * as rentalAgreementSol from "./rental_agreement.sol";
export type { rentalAgreementSol };
export type { MockToken } from "./MockToken";
