/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { XA_ChoreographyExample__factory } from "./XA_ChoreographyExample__factory";
export { XA_ProcessExecution__factory } from "./XA_ProcessExecution__factory";
