/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { XA_ChoreographyExample } from "./XA_ChoreographyExample";
export type { XA_ProcessExecution } from "./XA_ProcessExecution";
